//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADHashTable.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADHashTable.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Första kapitlet
        ///
        ///Den bok jag nu sätter mig ner att skriva måste verka meningslös på många - om jag alls vågar tänka mig, att &quot;många&quot; får läsa den - eftersom jag alldeles självmant, utan någons order, börjar ett sådant arbete och ändå inte själv är riktigt på det klara med vad avsikten är. Jag vill och måste, det är alltsammans. Allt mer och mer obönhörligt frågar man efter avsikten och planmässigheten i vad som göres och säges, så att helst inte ett ord ska falla på måfå - det är bara författaren till den [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string boye {
            get {
                return ResourceManager.GetString("boye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB
        ///abbedissa
        ///abbedissan
        ///abbedissans
        ///abbedissas
        ///abbedissor
        ///abbedissorna
        ///abbedissornas
        ///abbedissors
        ///abborrar
        ///abborrarna
        ///abborrarnas
        ///abborrars
        ///abborre
        ///abborren
        ///abborrens
        ///abborres
        ///abbot
        ///abbotar
        ///abbotarna
        ///abbotarnas
        ///abbotars
        ///abboten
        ///abbotens
        ///abbots
        ///abbé
        ///abbéer
        ///abbéerna
        ///abbéernas
        ///abbéers
        ///abbén
        ///abbéns
        ///abderit
        ///abderiten
        ///abderitens
        ///abderiter
        ///abderiterna
        ///abderiternas
        ///abderiters
        ///abderits
        ///abdikation
        ///abdikationen
        ///abdikationens
        ///abdikationer
        ///abdikationerna
        ///abdikationernas
        ///abdik [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ordlista {
            get {
                return ResourceManager.GetString("ordlista", resourceCulture);
            }
        }
    }
}
